spring:
  application:
    name: slack-service
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # 데이터베이스 스키마를 자동으로 업데이트
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 19500

jwt:
  secret:
    key: 4f71f168511a269e154e2687b65aefb9ca8b4415a860688bcb406c22eefb7f6f9be0aa85fc5b11463b61e61f206d4d95235eb9985181dfcaf9e1d627d4c1c8c0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
