POST http://localhost:19200/api/products
Content-Type: application/json

{
  "name": "product A",
  "stock": 15,
  "producerVendorId": "823365fd-602f-4575-9f1b-39736b1a1cef",
  "belongingHubId": "123e4567-e89b-12d3-a456-426614174000"
}


###
DELETE  http://localhost:19200/api/products/b29fa056-bc31-4613-858e-1746362e27cc

###
PATCH http://localhost:19200/api/products/5ef0f3f1-f4df-4cb2-9569-860c386c0e5a/stock/decrease
Content-Type: application/json

{
  "amount": 3
}

###
PATCH http://localhost:19200/api/products/9b73a334-0b92-4ced-a829-91fbf0331249/stock/increase
Content-Type: application/json

{
  "amount": 3
}

###
GET http://localhost:19200/api/products/2eefcc1e-9ad0-495c-8479-ebea7e2a6869

###
GET http://localhost:19200/api/products

###
GET http://localhost:19200/api/internal/products/eee4d247-2459-4ded-8186-a1b854db1261

###
PATCH http://localhost:19200/api/internal/products/4597b30b-a4e3-4946-9349-d9e2c8c16ecc/stock
Content-Type: application/json

{
  "amount": -30
}