# 1. OpenJDK 17 이미지 사용
FROM openjdk:17-jdk-alpine

# 2. 작업 디렉토리 설정
WORKDIR /app

# 3. 빌드된 JAR 파일을 컨테이너로 복사
COPY /build/libs/hub_service-0.0.1-SNAPSHOT.jar /app/hub_service.jar

# 4. 컨테이너 시작 시 JAR 파일 실행
ENTRYPOINT ["java", "-jar", "/app/hub_service.jar"]
