services:
# eureka
  eureka-service:
    build:
      context: ./server/
      dockerfile: Dockerfile
    container_name: eureka-service
    ports:
      - "19090:19090"
    networks:
      - msa-network

# vendor
  vendor-db:
    image: mysql:latest
    container_name: vendor-db
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: sparta-vendor
      MYSQL_USER: panjun
      MYSQL_PASSWORD: 0709
    ports:
      - "13306:3306"
    networks:
      - vendor-network

  vendor-service:
    build:
      context: ./vendor/
      dockerfile: Dockerfile
    container_name: vendor-service
    ports:
      - "9101:9101"
    depends_on:
      - eureka-service
      - vendor-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://vendor-db:3306/sparta-vendor
      SPRING_DATASOURCE_USERNAME: panjun
      SPRING_DATASOURCE_PASSWORD: 0709
    restart: always
    networks:
      - msa-network
      - vendor-network

# product
  product-db:
    image: mysql:latest
    container_name: product-db
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: sparta-product
      MYSQL_USER: panjun
      MYSQL_PASSWORD: 0709
    ports:
      - "23306:3306"
    networks:
      - product-network

  product-service:
    build:
      context: ./product/
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "9201:9201"
    depends_on:
      - eureka-service
      - product-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://product-db:3306/sparta-product
      SPRING_DATASOURCE_USERNAME: panjun
      SPRING_DATASOURCE_PASSWORD: 0709
    restart: always
    networks:
      - msa-network
      - product-network

# order
  order-db:
    image: mysql:latest
    container_name: order-db
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: sparta-order
      MYSQL_USER: panjun
      MYSQL_PASSWORD: 0709
    ports:
      - "33306:3306"
    networks:
      - order-network

  order-service:
    build:
      context: ./order/
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "9301:9301"
    depends_on:
      - eureka-service
      - order-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://order-db:3306/sparta-order
      SPRING_DATASOURCE_USERNAME: panjun
      SPRING_DATASOURCE_PASSWORD: 0709
    restart: always
    networks:
      - msa-network
      - order-network

# network
networks:
  msa-network:
    driver: bridge
  vendor-network:
    driver: bridge
  product-network:
    driver: bridge
  order-network:
    driver: bridge
