server:
  port: 19091

spring:
  data:
    redis:
      host: localhost
      port: 6379
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: slack-service
          uri: lb://slack-service
          predicates:
            - Path=/api/slacks/**

jwt:
  secret:
    key: 4f71f168511a269e154e2687b65aefb9ca8b4415a860688bcb406c22eefb7f6f9be0aa85fc5b11463b61e61f206d4d95235eb9985181dfcaf9e1d627d4c1c8c0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG