eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"

  tracing:
    sampling:
      probability: 1.0

  endpoints:
    web:
      exposure:
        include: actuator, prometheus

  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true