spring:
  application:
    name: auth-service

  jpa:
    hibernate:
      ddl-auto: update  # 데이터베이스 스키마를 자동으로 업데이트
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://auth-db:5432/auth
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver


server:
  port: 19400

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/

jwt:
  secret:
    key: 4f71f168511a269e154e2687b65aefb9ca8b4415a860688bcb406c22eefb7f6f9be0aa85fc5b11463b61e61f206d4d95235eb9985181dfcaf9e1d627d4c1c8c0

