###
POST http://localhost:19300/api/orders
Content-Type: application/json

{
  "orderProductId": "9b73a334-0b92-4ced-a829-91fbf0331249",
  "quantity": 4,
  "consumerVendorId": "823365fd-602f-4575-9f1b-39736b1a1cef"
}

###
DELETE http://localhost:19300/api/orders/e6e51827-20d1-4ef7-9728-af51b5fde057

###
GET http://localhost:19300/api/orders/e6e51827-20d1-4ef7-9728-af51b5fde057

###
GET http://localhost:19300/api/test

###
GET http://localhost:19300/api/kafka