### vendor-service -------------------------------------------------------------------------------
### 업체 등록
POST http://localhost:8080/api/vendors
Content-Type: application/json

{
  "name": "vendor name",
  "vendorType": "CONSUMER",
  "address": "vendor address",
  "vendorManagerUserId": "123e4567-e89b-12d3-a456-426614174000",
  "belongingHubId": "123e4567-e89b-12d3-a456-426614174000"
}

### 업체 삭제
DELETE http://localhost:8080/api/vendors/4978eda2-0e86-4a16-b64b-0015d02142c2

### 업체 단건 조회
GET http://localhost:8080/api/vendors/4978eda2-0e86-4a16-b64b-0015d02142c2

### 업체 목록 조회
GET http://localhost:8080/api/vendors

### product-service -------------------------------------------------------------------------------
### 상품 등록
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "product A",
  "stock": 1000000,
  "producerVendorId": "92da173d-351d-4c2f-8b2c-d1b138f38ad8",
  "belongingHubId": "123e4567-e89b-12d3-a456-426614174000"
}

### 상품 삭제
DELETE  http://localhost:8080/api/products/1c0ea43d-f504-4d85-84dd-ac7ca70e08c5

### 상품 재고 감소
PATCH http://localhost:8080/api/products/45da4c48-6456-437e-b954-cfcbbfba465e/stock/decrease
Content-Type: application/json

{
  "amount": 5
}

### 상품 재고 증가
PATCH http://localhost:8080/api/products/45da4c48-6456-437e-b954-cfcbbfba465e/stock/increase
Content-Type: application/json

{
  "amount": 5
}

### 상품 단건 조회
GET http://localhost:8080/api/products/45da4c48-6456-437e-b954-cfcbbfba465e

### 상품 목록 조회
GET http://localhost:8080/api/products

### order-service -------------------------------------------------------------------------------
### 주문 등록
POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "orderProductId": "992cceff-d039-472f-9d1d-233c7715a2f8",
  "quantity": 5,
  "consumerVendorId": "92da173d-351d-4c2f-8b2c-d1b138f38ad8"
}

### 주문 취소
PATCH http://localhost:8080/api/orders/1d42f05d-c74b-4c10-8b3c-608645b2c781/cancel

### 주문 삭제
DELETE http://localhost:8080/api/orders/9d66b98d-5a62-4aec-be05-d2cc8cd57ef7

### 주문 단건 조회
GET http://localhost:8080/api/orders/d0171d8c-1f92-4eee-af03-ba32c051e599

### 주문 목록 조회
GET http://localhost:8080/api/orders

### [배달 완료 이벤트 발행]
GET http://localhost:8080/api/test/c3395419-80e2-4536-81f1-be0ffcbbddad/1d42f05d-c74b-4c10-8b3c-608645b2c781